# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(821, 648)
        Register.setMinimumSize(QtCore.QSize(821, 648))
        Register.setMaximumSize(QtCore.QSize(821, 648))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/images/logo-gcg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Register.setWindowIcon(icon)
        Register.setStyleSheet("background-color: rgb(255, 226, 157);")
        self.centralwidget = QtWidgets.QWidget(Register)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 20, 211, 51))
        self.label.setObjectName("label")
        self.textCi = QtWidgets.QTextEdit(self.centralwidget)
        self.textCi.setGeometry(QtCore.QRect(70, 50, 181, 31))
        self.textCi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textCi.setObjectName("textCi")
        self.textSurname = QtWidgets.QTextEdit(self.centralwidget)
        self.textSurname.setGeometry(QtCore.QRect(70, 260, 181, 31))
        self.textSurname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textSurname.setObjectName("textSurname")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 230, 211, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 90, 211, 31))
        self.label_4.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 20, 181, 21))
        self.label_5.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.label_5.setObjectName("label_5")
        self.textName = QtWidgets.QTextEdit(self.centralwidget)
        self.textName.setGeometry(QtCore.QRect(70, 120, 181, 31))
        self.textName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textName.setObjectName("textName")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 370, 211, 31))
        self.label_6.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 520, 211, 51))
        self.label_7.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.label_7.setObjectName("label_7")
        self.textPhone = QtWidgets.QTextEdit(self.centralwidget)
        self.textPhone.setGeometry(QtCore.QRect(70, 570, 181, 31))
        self.textPhone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textPhone.setObjectName("textPhone")
        self.textName_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textName_2.setGeometry(QtCore.QRect(70, 190, 181, 31))
        self.textName_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textName_2.setObjectName("textName_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 160, 211, 31))
        self.label_8.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 261, 611))
        self.label_2.setStyleSheet("background-color: rgb(255, 199, 121);\n"
"border-radius: 50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 290, 211, 31))
        self.label_9.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.label_9.setObjectName("label_9")
        self.textSurname_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textSurname_2.setGeometry(QtCore.QRect(70, 330, 181, 31))
        self.textSurname_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textSurname_2.setObjectName("textSurname_2")
        self.register_2 = QtWidgets.QToolButton(self.centralwidget)
        self.register_2.setGeometry(QtCore.QRect(370, 500, 121, 121))
        self.register_2.setStyleSheet("border-style: none;\n"
"border-width: 6px;\n"
"border-color: rgb(0, 51, 102);\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 60px;")
        self.register_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/images/registrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.register_2.setIcon(icon1)
        self.register_2.setIconSize(QtCore.QSize(100, 100))
        self.register_2.setObjectName("register_2")
        self.principal = QtWidgets.QToolButton(self.centralwidget)
        self.principal.setGeometry(QtCore.QRect(590, 500, 121, 121))
        self.principal.setStyleSheet("border-style: none;\n"
"border-width: 6px;\n"
"border-color: rgb(0, 51, 102);\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 60px;")
        self.principal.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/images/volver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.principal.setIcon(icon2)
        self.principal.setIconSize(QtCore.QSize(100, 100))
        self.principal.setObjectName("principal")
        self.Mostrar = QtWidgets.QLabel(self.centralwidget)
        self.Mostrar.setGeometry(QtCore.QRect(350, 150, 401, 291))
        self.Mostrar.setStyleSheet("border-radius: 30px;")
        self.Mostrar.setText("")
        self.Mostrar.setObjectName("Mostrar")
        self.Mostrar_2 = QtWidgets.QLabel(self.centralwidget)
        self.Mostrar_2.setGeometry(QtCore.QRect(320, 120, 461, 351))
        self.Mostrar_2.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(255, 199, 121);")
        self.Mostrar_2.setText("")
        self.Mostrar_2.setObjectName("Mostrar_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 410, 181, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBusiness = QtWidgets.QComboBox(self.centralwidget)
        self.comboBusiness.setGeometry(QtCore.QRect(70, 490, 181, 31))
        self.comboBusiness.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBusiness.setObjectName("comboBusiness")
        self.comboBusiness.addItem("")
        self.comboBusiness.addItem("")
        self.comboBusiness.addItem("")
        self.comboBusiness.addItem("")
        self.comboBusiness.addItem("")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(70, 450, 211, 31))
        self.label_10.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.label_10.setObjectName("label_10")
        self.Mostrar_2.raise_()
        self.label_2.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.textSurname.raise_()
        self.label_5.raise_()
        self.textName.raise_()
        self.textPhone.raise_()
        self.textCi.raise_()
        self.textName_2.raise_()
        self.label_9.raise_()
        self.textSurname_2.raise_()
        self.register_2.raise_()
        self.principal.raise_()
        self.Mostrar.raise_()
        self.comboBox.raise_()
        self.comboBusiness.raise_()
        self.label_10.raise_()
        Register.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Register)
        self.statusbar.setObjectName("statusbar")
        Register.setStatusBar(self.statusbar)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Registro"))
        self.label.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:20pt; font-style:italic;\">Ingresar persona</span></p></body></html>"))
        self.label_3.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">Primer apelllido</span></p></body></html>"))
        self.label_4.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">Primer nombre</span></p></body></html>"))
        self.label_5.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">Cedula</span></p></body></html>"))
        self.label_6.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">Departamento</span></p></body></html>"))
        self.label_7.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:14pt;\">Teléfono</span></p></body></html>"))
        self.label_8.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">Segundo nombre</span></p></body></html>"))
        self.label_9.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">Segundo apelllido</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Register", "sistemas"))
        self.comboBox.setItemText(1, _translate("Register", "administración"))
        self.comboBox.setItemText(2, _translate("Register", "gerencia"))
        self.comboBox.setItemText(3, _translate("Register", "compras"))
        self.comboBox.setItemText(4, _translate("Register", "recursos humanos"))
        self.comboBox.setItemText(5, _translate("Register", "mantenimiento y limpieza"))
        self.comboBusiness.setItemText(0, _translate("Register", "VENSUCA"))
        self.comboBusiness.setItemText(1, _translate("Register", "GCG PROVEEDORES"))
        self.comboBusiness.setItemText(2, _translate("Register", "FULL TOOLS"))
        self.comboBusiness.setItemText(3, _translate("Register", "MTN"))
        self.comboBusiness.setItemText(4, _translate("Register", "SUMIVENTA"))
        self.label_10.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">Empresa</span></p></body></html>"))
